### ISSUE TITLE
[Question] How to get density maps from input image?

### ISSUE THREAD

**Issue by marcemq** [LoraLinH/Boosting-Crowd-Counting-via-Multifaceted-Attention#11]
Hello @LoraLinH :)

Thank you for sharing the code for the 'Boosting Crowd Counting via Multifaceted Attention' paper.

I'm intended to use it for initial step in a _crowd forecasting project_.
I was able to execute `test.py` file and see the mae and mse results 😊 

Now, I want to be able to given an input image get its density map. Checking the paper I think it's an output of the Regression Decoder, but I couldn't found it in the code, so would you please point me how to achieve this?

Big thank you in advance.

**Comment by LoraLinH** [comment]
You can obtain the density map by 'output = model(input)[0]' in the test.py.

Morales Quispe, Marcela ***@***.***> 于2023年5月26日周五 02:07写道：

**Comment by marcemq** [comment]
Hello @LoraLinH, thank you for your reply.

I've manage to write such output into an image for the very first iteration, this output is expected right?

![test](https://github.com/LoraLinH/Boosting-Crowd-Counting-via-Multifaceted-Attention/assets/21090606/e2da5105-341f-444e-8a3e-68b4ca4fd0e9)

Code to generate the image:
```
outputs = model(inputs)[0] # a tensor of [1,1,117,156] and values between 0-1
outImg = outputs[0][0].detach().cpu().numpy()
cv2.imwrite("test.png", outImg*255)
```
