### ISSUE TITLE
save_density_and_var.py

### ISSUE THREAD

**Issue by fengjingchehu** [LoraLinH/Boosting-Crowd-Counting-via-Multifaceted-Attention#17]
https://github.com/LoraLinH/Boosting-Crowd-Counting-via-Multifaceted-Attention/blob/95510df5607658978eecf857698edaf723376c5c/save_density_and_var.py#L53C1-L53C1
may should be changed into "  model = vgg19_trans().to(device) "

**Comment by LoraLinH** [comment]
Thanks

wanglin ***@***.***> 于2023年12月7日周四 16:13写道：
